apiVersion: v1
kind: Service
metadata:
  name: hasura-graphql-engine
spec:
  type: NodePort
  selector:
    app: hasura-graphql-engine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
