apiVersion: v2
name: keycloak
description: A Helm chart for Kubernetes
version: 1.0.0

dependencies:
  - name: keycloak
    version: "18.4.3"
    repository: "https://codecentric.github.io/helm-charts"
